#!/bin/bash

function createOrgIssuer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/orgissuer.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/orgissuer.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-orgissuer --tls.certfiles "${PWD}/organizations/fabric-ca/orgissuer/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-orgissuer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-orgissuer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-orgissuer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-orgissuer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/orgissuer.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy org1's CA cert to org1's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/orgissuer.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/orgissuer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/orgissuer.com/msp/tlscacerts/ca.crt"

  # Copy org1's CA cert to org1's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/orgissuer.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/orgissuer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/orgissuer.com/tlsca/tlsca.orgissuer.com-cert.pem"

  # Copy org1's CA cert to org1's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/orgissuer.com/ca"
  cp "${PWD}/organizations/fabric-ca/orgissuer/ca-cert.pem" "${PWD}/organizations/peerOrganizations/orgissuer.com/ca/ca.orgissuer.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-orgissuer --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/orgissuer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-orgissuer --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/orgissuer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-orgissuer --id.name orgissueradmin --id.secret orgissueradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/orgissuer/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-orgissuer -M "${PWD}/organizations/peerOrganizations/orgissuer.com/peers/peer0.orgissuer.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orgissuer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/orgissuer.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/orgissuer.com/peers/peer0.orgissuer.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-orgissuer -M "${PWD}/organizations/peerOrganizations/orgissuer.com/peers/peer0.orgissuer.com/tls" --enrollment.profile tls --csr.hosts peer0.orgissuer.com --csr.hosts localhost --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/orgissuer/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/orgissuer.com/peers/peer0.orgissuer.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/orgissuer.com/peers/peer0.orgissuer.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/orgissuer.com/peers/peer0.orgissuer.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/orgissuer.com/peers/peer0.orgissuer.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/orgissuer.com/peers/peer0.orgissuer.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/orgissuer.com/peers/peer0.orgissuer.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-orgissuer -M "${PWD}/organizations/peerOrganizations/orgissuer.com/users/User1@orgissuer.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orgissuer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/orgissuer.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/orgissuer.com/users/User1@orgissuer.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://orgissueradmin:orgissueradminpw@localhost:7054 --caname ca-orgissuer -M "${PWD}/organizations/peerOrganizations/orgissuer.com/users/Admin@orgissuer.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orgissuer/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/orgissuer.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/orgissuer.com/users/Admin@orgissuer.com/msp/config.yaml"
}

function createOrgVerifier() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/orgverifier.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/orgverifier.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-orgverifier --tls.certfiles "${PWD}/organizations/fabric-ca/orgverifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-orgverifier.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-orgverifier.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-orgverifier.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-orgverifier.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/orgverifier.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orgverifier's CA cert to orgverifier's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/orgverifier.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/orgverifier/ca-cert.pem" "${PWD}/organizations/peerOrganizations/orgverifier.com/msp/tlscacerts/ca.crt"

  # Copy orgverifier's CA cert to orgverifier's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/orgverifier.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/orgverifier/ca-cert.pem" "${PWD}/organizations/peerOrganizations/orgverifier.com/tlsca/tlsca.orgverifier.com-cert.pem"

  # Copy orgverifier's CA cert to orgverifier's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/orgverifier.com/ca"
  cp "${PWD}/organizations/fabric-ca/orgverifier/ca-cert.pem" "${PWD}/organizations/peerOrganizations/orgverifier.com/ca/ca.orgverifier.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-orgverifier --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/orgverifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-orgverifier --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/orgverifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-orgverifier --id.name orgverifieradmin --id.secret orgverifieradminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/orgverifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-orgverifier -M "${PWD}/organizations/peerOrganizations/orgverifier.com/peers/peer0.orgverifier.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orgverifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/orgverifier.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/orgverifier.com/peers/peer0.orgverifier.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-orgverifier -M "${PWD}/organizations/peerOrganizations/orgverifier.com/peers/peer0.orgverifier.com/tls" --enrollment.profile tls --csr.hosts peer0.orgverifier.com --csr.hosts localhost --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/orgverifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/orgverifier.com/peers/peer0.orgverifier.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/orgverifier.com/peers/peer0.orgverifier.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/orgverifier.com/peers/peer0.orgverifier.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/orgverifier.com/peers/peer0.orgverifier.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/orgverifier.com/peers/peer0.orgverifier.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/orgverifier.com/peers/peer0.orgverifier.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-orgverifier -M "${PWD}/organizations/peerOrganizations/orgverifier.com/users/User1@orgverifier.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orgverifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/orgverifier.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/orgverifier.com/users/User1@orgverifier.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://orgverifieradmin:orgverifieradminpw@localhost:8054 --caname ca-orgverifier -M "${PWD}/organizations/peerOrganizations/orgverifier.com/users/Admin@orgverifier.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orgverifier/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/orgverifier.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/orgverifier.com/users/Admin@orgverifier.com/msp/config.yaml"
}

function createOrgHolder() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/orgholder.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/orgholder.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orgholder --tls.certfiles "${PWD}/organizations/fabric-ca/orgholder/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orgholder.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orgholder.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orgholder.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orgholder.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/orgholder.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orgholder's CA cert to orgholder's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/orgholder.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/orgholder/ca-cert.pem" "${PWD}/organizations/peerOrganizations/orgholder.com/msp/tlscacerts/ca.crt"

  # Copy orgholder's CA cert to orgholder's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/orgholder.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/orgholder/ca-cert.pem" "${PWD}/organizations/peerOrganizations/orgholder.com/tlsca/tlsca.orgholder.com-cert.pem"

  # Copy orgholder's CA cert to orgholder's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/orgholder.com/ca"
  cp "${PWD}/organizations/fabric-ca/orgholder/ca-cert.pem" "${PWD}/organizations/peerOrganizations/orgholder.com/ca/ca.orgholder.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-orgholder --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/orgholder/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-orgholder --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/orgholder/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-orgholder --id.name OrgHolderadmin --id.secret OrgHolderadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/orgholder/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:9054 --caname ca-orgholder -M "${PWD}/organizations/peerOrganizations/orgholder.com/peers/peer0.orgholder.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orgholder/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/orgholder.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/orgholder.com/peers/peer0.orgholder.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:9054 --caname ca-orgholder -M "${PWD}/organizations/peerOrganizations/orgholder.com/peers/peer0.orgholder.com/tls" --enrollment.profile tls --csr.hosts peer0.orgholder.com --csr.hosts localhost --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/orgholder/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/orgholder.com/peers/peer0.orgholder.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/orgholder.com/peers/peer0.orgholder.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/orgholder.com/peers/peer0.orgholder.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/orgholder.com/peers/peer0.orgholder.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/orgholder.com/peers/peer0.orgholder.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/orgholder.com/peers/peer0.orgholder.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:9054 --caname ca-orgholder -M "${PWD}/organizations/peerOrganizations/orgholder.com/users/User1@orgholder.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orgholder/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/orgholder.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/orgholder.com/users/User1@orgholder.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://OrgHolderadmin:OrgHolderadminpw@localhost:9054 --caname ca-orgholder -M "${PWD}/organizations/peerOrganizations/orgholder.com/users/Admin@orgholder.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/orgholder/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/orgholder.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/orgholder.com/users/Admin@orgholder.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/legitifyapp.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/legitifyapp.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:10054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-10054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/legitifyapp.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/legitifyapp.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/legitifyapp.com/msp/tlscacerts/tlsca.legitifyapp.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/legitifyapp.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/legitifyapp.com/tlsca/tlsca.legitifyapp.com-cert.pem"

  # Register and enroll the orderers
  infoln "Registering orderer1"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering orderer2"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer2 --id.secret orderer2pw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering orderer3"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer3 --id.secret orderer3pw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering orderer4"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer4 --id.secret orderer4pw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Orderer 1
  infoln "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:10054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/msp/config.yaml"

  infoln "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:10054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls" --enrollment.profile tls --csr.hosts orderer.legitifyapp.com --csr.hosts localhost --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer.legitifyapp.com/msp/tlscacerts/tlsca.legitifyapp.com-cert.pem"

  # Orderer 2
  infoln "Generating the orderer2 msp"
  set -x
  fabric-ca-client enroll -u https://orderer2:orderer2pw@localhost:10054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer2.legitifyapp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer2.legitifyapp.com/msp/config.yaml"

  infoln "Generating the orderer2-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer2:orderer2pw@localhost:10054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer2.legitifyapp.com/tls" --enrollment.profile tls --csr.hosts orderer2.legitifyapp.com --csr.hosts localhost --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer2.legitifyapp.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer2.legitifyapp.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer2.legitifyapp.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer2.legitifyapp.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer2.legitifyapp.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer2.legitifyapp.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer2.legitifyapp.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer2.legitifyapp.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer2.legitifyapp.com/msp/tlscacerts/tlsca.legitifyapp.com-cert.pem"

  # Orderer 3
  infoln "Generating the orderer3 msp"
  set -x
  fabric-ca-client enroll -u https://orderer3:orderer3pw@localhost:10054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer3.legitifyapp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer3.legitifyapp.com/msp/config.yaml"

  infoln "Generating the orderer3-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer3:orderer3pw@localhost:10054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer3.legitifyapp.com/tls" --enrollment.profile tls --csr.hosts orderer3.legitifyapp.com --csr.hosts localhost --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer3.legitifyapp.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer3.legitifyapp.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer3.legitifyapp.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer3.legitifyapp.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer3.legitifyapp.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer3.legitifyapp.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer3.legitifyapp.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer3.legitifyapp.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer3.legitifyapp.com/msp/tlscacerts/tlsca.legitifyapp.com-cert.pem"

  # Orderer 4
  infoln "Generating the orderer4 msp"
  set -x
  fabric-ca-client enroll -u https://orderer4:orderer4pw@localhost:10054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer4.legitifyapp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer4.legitifyapp.com/msp/config.yaml"

  infoln "Generating the orderer4-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer4:orderer4pw@localhost:10054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer4.legitifyapp.com/tls" --enrollment.profile tls --csr.hosts orderer4.legitifyapp.com --csr.hosts localhost --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer4.legitifyapp.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer4.legitifyapp.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer4.legitifyapp.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer4.legitifyapp.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer4.legitifyapp.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer4.legitifyapp.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer4.legitifyapp.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer4.legitifyapp.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/legitifyapp.com/orderers/orderer4.legitifyapp.com/msp/tlscacerts/tlsca.legitifyapp.com-cert.pem"

  # Admin
  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:10054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/legitifyapp.com/users/Admin@legitifyapp.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/legitifyapp.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/legitifyapp.com/users/Admin@legitifyapp.com/msp/config.yaml"
}
